server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: verdantiq-gateway
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DB_NAME:VerdantIQ}
      auto-index-creation: true

management:
  endpoint:
    health:
      show-details: always

verdantiq:
  ml-service-url: "${ML_SERVICE_URL:https://verdantiq-ml-gateway.onrender.com}"
  internal-service-key: "${INTERNAL_SERVICE_KEY}"
  jwt:
    secret: "${JWT_SECRET:VerdantIQSecretKeyForJwtAuthentication32BytesLongMin!}"
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
