import { NextRequest, NextResponse } from 'next/server';
import { getMongoDb } from '@/lib/mongodb';

const INITIAL_INSTITUTIONS_SEED = [
  {
    id: 'inst-01',
    name: 'Pacific State University System',
    code: 'PSU',
    domain: 'institution.org',
    domainDNS: 'institution.org',
    regionDistrict: 'District 1 (Bay Area North)',
    lat: 37.7749,
    lng: -122.4194,
    status: 'active',
    studentCount: 24500,
    deptCount: 18,
    currentEUI: 112.4,
    targetEUI: 110.0,
    carbonIntensity: 184.2,
    targetCarbonIntensity: 200.0,
    forecastAccuracyPct: 94.8,
    forecastErrorMapePct: 5.2,
    targetDistanceScore: 92,
    complianceRate: 96.5,
    supportFlagged: false,
    provisioningStatus: 'provisioned',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'inst-02',
    name: 'Pacific State University',
    code: 'PSU-EDU',
    domain: 'pacific.edu',
    domainDNS: 'pacific.edu',
    regionDistrict: 'District 1 (Bay Area North)',
    lat: 37.7760,
    lng: -122.4200,
    status: 'active',
    studentCount: 18200,
    deptCount: 14,
    currentEUI: 108.2,
    targetEUI: 105.0,
    carbonIntensity: 175.0,
    targetCarbonIntensity: 190.0,
    forecastAccuracyPct: 95.1,
    forecastErrorMapePct: 4.9,
    targetDistanceScore: 95,
    complianceRate: 98.0,
    supportFlagged: false,
    provisioningStatus: 'provisioned',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'inst-03',
    name: 'Stanford University',
    code: 'STANFORD',
    domain: 'stanford.edu',
    domainDNS: 'stanford.edu',
    regionDistrict: 'District 2 (Silicon Corridor)',
    lat: 37.4275,
    lng: -122.1697,
    status: 'active',
    studentCount: 17000,
    deptCount: 20,
    currentEUI: 95.4,
    targetEUI: 90.0,
    carbonIntensity: 130.0,
    targetCarbonIntensity: 150.0,
    forecastAccuracyPct: 97.2,
    forecastErrorMapePct: 2.8,
    targetDistanceScore: 97,
    complianceRate: 99.1,
    supportFlagged: false,
    provisioningStatus: 'provisioned',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'inst-04',
    name: 'Massachusetts Institute of Technology',
    code: 'MIT',
    domain: 'mit.edu',
    domainDNS: 'mit.edu',
    regionDistrict: 'District 3 (Northwest Coastal)',
    lat: 42.3601,
    lng: -71.0942,
    status: 'active',
    studentCount: 11800,
    deptCount: 16,
    currentEUI: 92.1,
    targetEUI: 88.0,
    carbonIntensity: 120.5,
    targetCarbonIntensity: 140.0,
    forecastAccuracyPct: 98.0,
    forecastErrorMapePct: 2.0,
    targetDistanceScore: 99,
    complianceRate: 99.5,
    supportFlagged: false,
    provisioningStatus: 'provisioned',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'inst-05',
    name: 'UC Berkeley',
    code: 'UCB',
    domain: 'berkeley.edu',
    domainDNS: 'berkeley.edu',
    regionDistrict: 'District 1 (Bay Area North)',
    lat: 37.8719,
    lng: -122.2585,
    status: 'active',
    studentCount: 45000,
    deptCount: 25,
    currentEUI: 110.5,
    targetEUI: 100.0,
    carbonIntensity: 160.0,
    targetCarbonIntensity: 180.0,
    forecastAccuracyPct: 94.0,
    forecastErrorMapePct: 6.0,
    targetDistanceScore: 91,
    complianceRate: 95.0,
    supportFlagged: false,
    provisioningStatus: 'provisioned',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'inst-06',
    name: 'Harvard University',
    code: 'HARVARD',
    domain: 'harvard.edu',
    domainDNS: 'harvard.edu',
    regionDistrict: 'District 3 (Northwest Coastal)',
    lat: 42.3770,
    lng: -71.1167,
    status: 'active',
    studentCount: 23000,
    deptCount: 22,
    currentEUI: 102.0,
    targetEUI: 95.0,
    carbonIntensity: 140.0,
    targetCarbonIntensity: 160.0,
    forecastAccuracyPct: 96.5,
    forecastErrorMapePct: 3.5,
    targetDistanceScore: 96,
    complianceRate: 98.5,
    supportFlagged: false,
    provisioningStatus: 'provisioned',
    createdAt: new Date().toISOString(),
  }
];

const INITIAL_USERS_SEED = [
  {
    id: 'usr_sys_01',
    name: 'Residential User',
    email: 'user@verdantiq.org',
    role: 'user',
    tenantId: 'tenant_res_user',
    department: 'Residential Sector',
    createdAt: new Date().toISOString(),
    provider: 'email',
    isVerified: true,
  },
  {
    id: 'usr_sys_02',
    name: 'Student Learner',
    email: 'student@institution.org',
    role: 'student',
    tenantId: 'tenant_institution_org',
    institution: 'Academic Partner Institution',
    department: 'Environmental Engineering',
    isVerifiedStudent: true,
    isVerified: true,
    createdAt: new Date().toISOString(),
    provider: 'google',
  },
  {
    id: 'usr_sys_03',
    name: 'Department Moderator',
    email: 'dept@institution.org',
    role: 'dept',
    tenantId: 'tenant_institution_org',
    institution: 'Academic Partner Institution',
    department: 'Facility Science',
    isVerified: true,
    createdAt: new Date().toISOString(),
    provider: 'email',
  },
  {
    id: 'usr_sys_04',
    name: 'Institution Admin',
    email: 'admin@institution.org',
    role: 'institution',
    tenantId: 'tenant_institution_org',
    institution: 'Academic Partner Institution',
    isVerified: true,
    createdAt: new Date().toISOString(),
    provider: 'google',
  },
  {
    id: 'usr_sys_05',
    name: 'Regional Admin',
    email: 'region@tn.gov.in',
    role: 'region',
    tenantId: 'tenant_tn_district_board',
    institution: 'Regional District Governance Board',
    isVerified: true,
    createdAt: new Date().toISOString(),
    provider: 'outlook',
  },
  {
    id: 'usr_sys_06',
    name: 'Platform Admin',
    email: 'admin@verdantiq.io',
    role: 'admin',
    tenantId: 'tenant_verdantiq_core',
    isVerified: true,
    createdAt: new Date().toISOString(),
    provider: 'google',
  },
];

export async function GET(req: NextRequest) {
  try {
    const db = await getMongoDb();
    if (!db) {
      return NextResponse.json({
        success: true,
        message: 'MongoDB connection string pending; in-memory database simulation active.',
        seeded: false,
      });
    }

    const instCol = db.collection('institutions');
    const instCount = await instCol.countDocuments();
    if (instCount === 0) {
      await instCol.insertMany(INITIAL_INSTITUTIONS_SEED);
    }

    const userCol = db.collection('users');
    const userCount = await userCol.countDocuments();
    if (userCount === 0) {
      await userCol.insertMany(INITIAL_USERS_SEED);
    }

    return NextResponse.json({
      success: true,
      message: 'Database initialized and seeded successfully.',
      institutionsCount: await instCol.countDocuments(),
      usersCount: await userCol.countDocuments(),
    });
  } catch (error: any) {
    return NextResponse.json({ error: error.message || 'Database init error' }, { status: 500 });
  }
}
